/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ScheduledRouteImport } from './routes/scheduled'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChecklistsRouteImport } from './routes/checklists'
import { Route as AuditsRouteImport } from './routes/audits'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduledRoute = ScheduledRouteImport.update({
  id: '/scheduled',
  path: '/scheduled',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklistsRoute = ChecklistsRouteImport.update({
  id: '/checklists',
  path: '/checklists',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditsRoute = AuditsRouteImport.update({
  id: '/audits',
  path: '/audits',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audits': typeof AuditsRoute
  '/checklists': typeof ChecklistsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/scheduled': typeof ScheduledRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/users': typeof UsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audits': typeof AuditsRoute
  '/checklists': typeof ChecklistsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/scheduled': typeof ScheduledRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/users': typeof UsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audits': typeof AuditsRoute
  '/checklists': typeof ChecklistsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/scheduled': typeof ScheduledRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/users': typeof UsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audits'
    | '/checklists'
    | '/dashboard'
    | '/login'
    | '/reports'
    | '/scheduled'
    | '/search'
    | '/settings'
    | '/templates'
    | '/users'
    | '/api/auth/$'
    | '/api/rpc/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audits'
    | '/checklists'
    | '/dashboard'
    | '/login'
    | '/reports'
    | '/scheduled'
    | '/search'
    | '/settings'
    | '/templates'
    | '/users'
    | '/api/auth/$'
    | '/api/rpc/$'
  id:
    | '__root__'
    | '/'
    | '/audits'
    | '/checklists'
    | '/dashboard'
    | '/login'
    | '/reports'
    | '/scheduled'
    | '/search'
    | '/settings'
    | '/templates'
    | '/users'
    | '/api/auth/$'
    | '/api/rpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditsRoute: typeof AuditsRoute
  ChecklistsRoute: typeof ChecklistsRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  ReportsRoute: typeof ReportsRoute
  ScheduledRoute: typeof ScheduledRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  TemplatesRoute: typeof TemplatesRoute
  UsersRoute: typeof UsersRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scheduled': {
      id: '/scheduled'
      path: '/scheduled'
      fullPath: '/scheduled'
      preLoaderRoute: typeof ScheduledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checklists': {
      id: '/checklists'
      path: '/checklists'
      fullPath: '/checklists'
      preLoaderRoute: typeof ChecklistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audits': {
      id: '/audits'
      path: '/audits'
      fullPath: '/audits'
      preLoaderRoute: typeof AuditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditsRoute: AuditsRoute,
  ChecklistsRoute: ChecklistsRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  ReportsRoute: ReportsRoute,
  ScheduledRoute: ScheduledRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  TemplatesRoute: TemplatesRoute,
  UsersRoute: UsersRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
